### ISSUE TITLE
Scorecard period comparison data not correct

### ISSUE THREAD

**Issue by rylanczuczman** [Gladior-B-V/linkedin-company-connector#7]
Hi guys, sorry me again! 

I've set up a full LinkedIn dashboard in Looker Studio, but have noticed that scorecards don't pull through historical data, whereas tables and charts do - is this something to do with the way the API works?

As an example, I can look back over many months in a chart when looking at impressions, but it only seems to populate in the scorecard from when I linked the connector to Looker Studio, any help would be great appreciated!

Tagging for visibility @zoedufrenne

**Comment by zoedufrenne** [comment]
Hi @rylanczuczman, as you can see in the dashboard, the tables and charts show only data for a period of +/- 3 months. You will see the different posts but not the results of the metrics. This is because of the metrics from posts are not working with the date selector but with the created date. The score cards are working with the date selector, but the max. amount of  +/- 3 months (90 days). See also the API documentation of the LinkedIn connector.
